# =================================================================
# playbook_3_attach_disk.yml - 剧本3: 为第二批附加硬盘
# =================================================================
---
- name: "Stage 3: Attach Extra Disk to Batch 2 VMs"
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
    - name: "Attach a {{ batch2_extra_disk_gb }}GB disk to {{ item.name }}"
      community.vmware.vmware_guest_disk:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ item.name }}"
        disk:
          - size_gb: "{{ batch2_extra_disk_gb }}"
            type: thin
            datastore: "{{ vcenter_datastore }}"
            scsi_controller: 1 # 使用不同的控制器以避免与系统盘冲突
            unit_number: 0 # SCSI unit number for the disk on controller 1
            scsi_type: 'paravirtual'
            state: present
      loop: "{{ ocp_vms }}"

