# =================================================================
# playbook_2_create_batch2.yml - 剧本2: 创建第二批虚拟机
# =================================================================
---
- name: "Stage 2: Provision Batch 2 VMs"
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
    # - name: Get all folders
    #   community.vmware.vmware_folder_info:
    #     hostname: '{{ vcenter_hostname }}'
    #     username: '{{ vcenter_username }}'
    #     password: '{{ vcenter_password }}'
    #     validate_certs: no
    #     datacenter: '{{ vcenter_datacenter }}'
    #   register: v

    # - debug:
    #     msg: "{{ v.folder_info }}"

    - name: "Create Batch 2 VM: {{ item.name }}"
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ vcenter_datacenter }}"
        cluster: "{{ vcenter_cluster }}"
        # 如果 vm_folder 变量为空, `default(omit)` 会让 Ansible 忽略此参数。
        folder: "{{ vm_folder | default(omit) }}"
        name: "{{ item.name }}"
        state: poweredoff
        guest_id: "{{ guest_id }}"
        hardware:
          num_cpus: "{{ item.num_cpus }}"
          memory_mb: "{{ item.memory_mb }}"
        disk:
          - size_gb: "{{ item.disk1_gb }}"
            type: thin
            datastore: "{{ vcenter_datastore }}"
        networks:
          - name: "{{ vm_network }}"
            device_type: vmxnet3
        cdrom:
          - type: iso
            iso_path: "{{ vm_iso_path }}"
            state: present
            controller_number: 0
            unit_number: 0
      loop: "{{ ocp_vms }}"

    # --- 步骤 2: 修改现有虚拟机以启用 disk.EnableUUID ---
    - name: "Step 2: Enable disk UUID on VM {{ item.name }}"
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ vcenter_datacenter }}"
        folder: "{{ vm_folder | default(omit) }}"
        name: "{{ item.name }}"
        # 仅修改 customvalues，不改变其他任何东西
        customvalues:
          - key: 'disk.EnableUUID'
            value: '1'
        # 可以选择在这里开机
        state: poweredoff
      loop: "{{ ocp_vms }}"
      register: final_vm_state # 将最终状态（包含MAC地址）注册到变量中

    # --- (新) 步骤 3: 输出新创建虚拟机的 MAC 地址 ---
    - name: "Step 3: Display MAC addresses for created VMs"
      ansible.builtin.debug:
        msg: "VM '{{ item.item.name }}' has MAC address: {{ item.instance.mac_address }}"
      loop: "{{ final_vm_state.results }}"
      when:
        - item.instance is defined
        - item.instance.mac_address is defined