---
- name: Listen for Prometheus alerts and trigger AAP workflow
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Process Prometheus Alert
      condition: event.payload.alerts is defined
      action:
        run_workflow_template:
          name: "workflow-incident-change-request" # Placeholder: Replace with your actual AAP Workflow Template name
          organization: "Default" # Placeholder: Replace with your actual AAP Organization name
          extra_vars:
            prometheus_alert_content: "{{ event.payload | to_json }}"