---
- name: Automate SNOW 
  hosts: localhost
  connection: local
  collections:
    - servicenow.itsm

  vars:
    # incident_number_cached is expected to be passed as an extra var or from a previous workflow step
    prometheus_alert_content: "{{ ansible_eda.event.payload | default('N/A') }}"

  tasks:
    - debug:
        msg: "host: {{ snow_instance }}"
    - debug:
        msg: "username: {{ snow_username }}"

    # Always give your tasks a useful name
    - name: Create incident

      # This task leverages the 'incident' module from the 'itsm' collection 
      # within the 'servicenow' namespace
      servicenow.itsm.incident:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        state: new
        caller: "{{ snow_username }}"

        # Feel free to modify this line
        short_description: "User created a new incident using Ansible Automation Platform - {{ lookup('pipe', \"date '+%Y-%m-%d %H:%M:%S'\") }}"

        # These fields can also contain different variables from previous workflow steps,
        # environment variables, etc.. Feel free to modify this line
        description: "User {{ snow_username }} successfully created a new incident! Date: {{ lookup('pipe', \"date '+%Y-%m-%d %H:%M:%S'\") }}\nPrometheus Alert Content:\n{{ prometheus_alert_content | default('N/A') }}"
        impact: low
        urgency: low
      
      # Register the output of this task for use within subsequent tasks
      register: new_incident

    - name: Add additional comments to incident
      servicenow.itsm.incident:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        state: present
        number: "{{ new_incident.record.number }}"
        other:
          work_notes: "User {{ snow_username }} successfully created a new incident! Date: {{ lookup('pipe', \"date '+%Y-%m-%d %H:%M:%S'\") }}\nPrometheus Alert Content:\n{{ prometheus_alert_content | default('N/A') }}"

    - set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"
        cacheable: true

    - name: Set incident_number_cached as a statistic for workflow
      ansible.builtin.set_stats:
        data:
          incident_number_cached: "{{ new_incident.record.number }}"

    - debug:

        # Use the output of the incident creation task to display the incident number
        msg: "A new incident has been created: {{ new_incident.record.number }}"

